spring.application.name=backend

server.servlet.context-path=/api/v1
server.port=${PORT:8080}

app.base-url=${BASE_URL}

#Database keys
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

#for mail validations
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.frontend-url=${FRONTEND_URL}

brevo.api.key=${BREVO_API_KEY}

google.oauth.client-id=${GOOGLE_OAUTH_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
google.oauth.refresh-token=${GOOGLE_OAUTH_REFRESH_TOKEN}
gmail.sender.address=${GMAIL_SENDER_ADDRESS}

# AI Integration
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.5-flash-lite
spring.ai.google.genai.chat.temperature=0.5

# Cloudenary setup to save files
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY}
cloudinary.api-secret=${CLOUDINARY_SECRET}

#JWT Keys
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG

spring.mail.properties.mail.debug=true